[binaries]
c = 'aarch64-none-elf-gcc'
cpp = 'aarch64-none-elf-g++'
ar = 'aarch64-none-elf-gcc-ar'
strip = 'aarch64-none-elf-strip'
pkgconfig = '/opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-pkg-config'
# We need a wrapper to run switch binaries, but for now we set it to false
exe_wrapper = ['echo', 'Skipping execution']

[properties]
needs_exe_wrapper = true
# Important: Force these flags to ensure we link against libnx
c_args = ['-D__SWITCH__', '-march=armv8-a', '-mtune=cortex-a57', '-mtp=soft', '-fPIE']
cpp_args = ['-D__SWITCH__', '-march=armv8-a', '-mtune=cortex-a57', '-mtp=soft', '-fPIE']
link_args = ['-specs=/opt/devkitpro/libnx/switch.specs', '-march=armv8-a', '-mtune=cortex-a57', '-mtp=soft', '-fPIE']

[host_machine]
system = 'switch'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'