[binaries]
c = 'aarch64-none-elf-gcc'
cpp = 'aarch64-none-elf-g++'
ar = 'aarch64-none-elf-gcc-ar'
strip = 'aarch64-none-elf-strip'
pkgconfig = 'pkg-config'
exe_wrapper = ['echo', 'Skipping execution']  # Prevent Meson from trying to run built Switch binaries

[properties]
needs_exe_wrapper = true
sys_root = '/opt/devkitpro'
pkg_config_libdir = '/opt/devkitpro/portlibs/switch/lib/pkgconfig:/opt/devkitpro/libnx/lib/pkgconfig'

[built-in options]
# compile‑time include paths
c_args = ['-D__SWITCH__', '-DMKXP_BACKEND_GLES2', '-Dunix', '-march=armv8-a', '-mtune=cortex-a57', '-mtp=soft', '-fPIE', '-I/opt/devkitpro/libnx/include', '-I/opt/devkitpro/portlibs/switch/include', '-I/workspace/libs/ruby-switch/include/ruby-3.2.0', '-I/workspace/libs/ruby-switch/include/ruby-3.2.0/aarch64-linux', '-I/workspace/libs/physfs-switch/include', '-I/workspace/libs/SDL_sound-switch/include']
cpp_args = ['-D__SWITCH__', '-DMKXP_BACKEND_GLES2', '-Dunix', '-march=armv8-a', '-mtune=cortex-a57', '-mtp=soft', '-fPIE', '-I/opt/devkitpro/libnx/include', '-I/opt/devkitpro/portlibs/switch/include', '-I/workspace/libs/ruby-switch/include/ruby-3.2.0', '-I/workspace/libs/ruby-switch/include/ruby-3.2.0/aarch64-linux', '-I/workspace/libs/physfs-switch/include', '-I/workspace/libs/SDL_sound-switch/include']
# link‑time search paths
c_link_args = ['-specs=/opt/devkitpro/libnx/switch.specs', '-L/opt/devkitpro/portlibs/switch/lib', '-L/opt/devkitpro/libnx/lib', '-L/workspace/libs/ruby-switch/lib', '-L/workspace/libs/physfs-switch/lib', '-L/workspace/libs/SDL_sound-switch/lib']
cpp_link_args = ['-specs=/opt/devkitpro/libnx/switch.specs', '-L/opt/devkitpro/portlibs/switch/lib', '-L/opt/devkitpro/libnx/lib', '-L/workspace/libs/ruby-switch/lib', '-L/workspace/libs/physfs-switch/lib', '-L/workspace/libs/SDL_sound-switch/lib']

[host_machine]
system = 'switch'
cpu_family = 'aarch64'
cpu = 'cortex-a57'
endian = 'little'
